### ISSUE TITLE
Error when adding more than one two-zone receiver

### ISSUE THREAD

**Issue by Austin519** [ToddGreenfield/homebridge-onkyo#102]
**Confirm you have checked the WIKI for troubleshooting first**
_Fill out and check (`[x]`) the boxes which apply.
- Homebridge version: HOOBS 3.3.5
- Plugin version: 2021.15.1
- OS, including release name/version: 
- [X] Homebridge-Onkyo installed via OS/distribution mechanisms
- [ ] You installed using homebridge-config-ui-x
- [ ] You enabled homebridge debug output

**Describe the bug**
I have three two-zone receivers.  Installing the first receiver works fine for both zones (any of the three).  As soon as I add a second receiver (even a single zone), I start seeing the error below.  I am still able to add all three receivers to HomeKit (6 Homekit objects, because each receiver has two zones), but there is clearly a communication issue because the receivers do not respond to commands through HomeKit and sometimes will respond to commands sent to another receiver.

**To Reproduce**
Information on your Onkyo receiver:
1. Integra DRX 5.2 (192.168.2.22)
2. Integra DRX 5.2 (192.168.2.23)
3. Integra DRX 5.2 (192.168.2.24)

**Information on your configuration:**
1. HOOBS 3.3.5 , latest (192.168.2.172)
2. Running on Hoobs device (Raspberry Pi 3 rev 1.3)
3. Config file:
"platform": "Onkyo",
            "plugin_map": {
                "plugin_name": "homebridge-onkyo"
            },
            "receivers": [
                {
                    "model": "DTR-70.2",
                    "ip_address": "192.168.2.22",
                    "poll_status_interval": "3000",
                    "name": "Den Receiver",
                    "zone": "main",
                    "default_volume": "50",
                    "max_volume": "80",
                    "map_volume_100": true,
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "U-Verse"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "Widi"
                        }
                    ],
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true
                },
                {
                    "model": "DTR-70.2",
                    "ip_address": "192.168.2.22",
                    "poll_status_interval": "3000",
                    "name": "Kitchen Receiver",
                    "zone": "zone2",
                    "default_volume": "50",
                    "max_volume": "80",
                    "map_volume_100": true,
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "U-Verse"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "Widi"
                        }
                    ],
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true
                },
                {
                    "model": "DTR-70.2",
                    "ip_address": "192.168.2.23",
                    "poll_status_interval": "3000",
                    "name": "Master Bed Receiver",
                    "zone": "main",
                    "default_volume": "50",
                    "max_volume": "80",
                    "map_volume_100": true,
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "U-Verse"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "Widi"
                        }
                    ],
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true
                },
                {
                    "model": "DTR-70.2",
                    "ip_address": "192.168.2.23",
                    "poll_status_interval": "3000",
                    "name": "Master Bath Receiver",
                    "zone": "zone2",
                    "default_volume": "50",
                    "max_volume": "80",
                    "map_volume_100": true,
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "U-Verse"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "Widi"
                        }
                    ],
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true
                },
                {
                    "model": "DTR-70.2",
                    "ip_address": "192.168.2.24",
                    "poll_status_interval": "3000",
                    "name": "Guest Bed Receiver",
                    "zone": "main",
                    "default_volume": "50",
                    "max_volume": "80",
                    "map_volume_100": true,
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "U-Verse"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "Widi"
                        }
                    ],
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true
                },
                {
                    "model": "DTR-70.2",
                    "ip_address": "192.168.2.24",
                    "poll_status_interval": "3000",
                    "name": "Patio Receiver",
                    "zone": "zone2",
                    "default_input": "dvd",
                    "default_volume": "50",
                    "max_volume": "80",
                    "map_volume_100": true,
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "U-Verse"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "Widi"
                        }
                    ],
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true
                }
            ]
        }

**Information from the log:**
4/20/2021, 2:13:19 PM Initializing HAP-NodeJS v0.9.3...
4/20/2021, 2:13:22 PM Loaded plugin 'homebridge-onkyo'
4/20/2021, 2:13:22 PM [4/20/2021, 1:13:22 PM] Registering platform 'homebridge-onkyo.Onkyo'
4/20/2021, 2:13:24 PM [Onkyo] Initializing Onkyo platform...
4/20/2021, 2:13:24 PM [Onkyo] **************************************************************
4/20/2021, 2:13:24 PM [Onkyo]   homebridge-onkyo version 2021.15.1
4/20/2021, 2:13:24 PM [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
4/20/2021, 2:13:24 PM [Onkyo] **************************************************************
4/20/2021, 2:13:24 PM [Onkyo] start success...
4/20/2021, 2:13:24 PM [Onkyo] **************************************************************
4/20/2021, 2:13:24 PM [Onkyo]   homebridge-onkyo version 2021.15.1
4/20/2021, 2:13:24 PM [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
4/20/2021, 2:13:24 PM [Onkyo] **************************************************************
4/20/2021, 2:13:24 PM [Onkyo] start success...
4/20/2021, 2:13:24 PM [Onkyo] **************************************************************
4/20/2021, 2:13:24 PM [Onkyo]   homebridge-onkyo version 2021.15.1
4/20/2021, 2:13:24 PM [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
4/20/2021, 2:13:24 PM [Onkyo] **************************************************************
4/20/2021, 2:13:24 PM [Onkyo] start success...
4/20/2021, 2:13:26 PM Preparing Advertiser for 'Den Receiver F794' using bonjour-hap backend!
4/20/2021, 2:13:26 PM Preparing Advertiser for 'Kitchen Receiver 878F' using bonjour-hap backend!
4/20/2021, 2:13:26 PM Preparing Advertiser for 'Master Bed Receiver D3EF' using bonjour-hap backend!
4/20/2021, 2:13:26 PM Preparing Advertiser for 'HOOBS E74E' using bonjour-hap backend!
4/20/2021, 2:13:26 PM Starting to advertise 'Den Receiver F794' using bonjour-hap backend!
4/20/2021, 2:13:26 PM Den Receiver F794 is running on port 34167.
4/20/2021, 2:13:26 PM Please add [Den Receiver F794] manually in Home app. Setup Code: 031-45-154
4/20/2021, 2:13:26 PM Starting to advertise 'Kitchen Receiver 878F' using bonjour-hap backend!
4/20/2021, 2:13:26 PM Kitchen Receiver 878F is running on port 41441.
4/20/2021, 2:13:26 PM Please add [Kitchen Receiver 878F] manually in Home app. Setup Code: 031-45-154
4/20/2021, 2:13:26 PM Starting to advertise 'Master Bed Receiver D3EF' using bonjour-hap backend!
4/20/2021, 2:13:26 PM Master Bed Receiver D3EF is running on port 35097.
4/20/2021, 2:13:26 PM Please add [Master Bed Receiver D3EF] manually in Home app. Setup Code: 031-45-154
4/20/2021, 2:13:26 PM Starting to advertise 'HOOBS E74E' using bonjour-hap backend!
4/20/2021, 2:13:26 PM Bridge is running on port 51826.
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (server_error) Server error on 192.168.2.23:60128 - Error: connect EALREADY 192.168.2.23:60128 - Local (192.168.2.172:44248)
    at internalConnect (net.js:921:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at net.js:1011:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EALREADY',
  code: 'EALREADY',
  syscall: 'connect',
  address: '192.168.2.23',
  port: 60128
}
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (server_error) Server error on 192.168.2.23:60128 - Error: connect EALREADY 192.168.2.23:60128 - Local (192.168.2.172:44248)
    at internalConnect (net.js:921:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at net.js:1011:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EALREADY',
  code: 'EALREADY',
  syscall: 'connect',
  address: '192.168.2.23',
  port: 60128
}
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (server_error) Server error on 192.168.2.23:60128 - Error: connect EALREADY 192.168.2.23:60128 - Local (192.168.2.172:44248)
    at internalConnect (net.js:921:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at net.js:1011:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EALREADY',
  code: 'EALREADY',
  syscall: 'connect',
  address: '192.168.2.23',
  port: 60128
}
4/20/2021, 2:13:26 PM [Den Receiver F794@Den Receiver@Active Identifier] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/20/2021, 2:13:26 PM [Kitchen Receiver 878F@Kitchen Receiver@Active Identifier] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/20/2021, 2:13:26 PM [Master Bed Receiver D3EF@Master Bed Receiver@Active Identifier] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLIQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLIQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLIQSTN"
4/20/2021, 2:13:26 PM [Onkyo] getInputState - INPUT QRY: ERROR - current i_state: 1
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "AMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "AMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "AMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "MVLQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "MVLQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "MVLQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZPWQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZPWQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZPWQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLZQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLZQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLZQSTN"
4/20/2021, 2:13:26 PM [Onkyo] getInputState - INPUT QRY: ERROR - current i_state: 1
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZVLQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZVLQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZVLQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLIQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLIQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLIQSTN"
4/20/2021, 2:13:26 PM [Onkyo] getInputState - INPUT QRY: ERROR - current i_state: 1
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "AMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "AMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "AMTQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "MVLQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "MVLQSTN"
4/20/2021, 2:13:26 PM [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "MVLQSTN"

**Expected behavior**
Ability to load and control receivers.

**Comment by Austin519** [comment]
This may be the same issue as this one: https://github.com/ToddGreenfield/homebridge-onkyo/issues/11.  I don't want to have to run three separate homebridge instances as a workaround if possible.
