### ISSUE TITLE
Plugin dies after configuration + continuously throws errors

### ISSUE THREAD

**Issue by camielverdult** [ToddGreenfield/homebridge-onkyo#116]
**Confirm you have checked the WIKI for troubleshooting first**
_Fill out and check (`[x]`) the boxes which apply.
- Homebridge version: Homebridge v1.3.4
- Plugin version: homebridge-onkyo v2021.28.1 
- OS, including release name/version: Docker container on Alpine Linux (3.12.7)
- [x] Homebridge-Onkyo installed via OS/distribution mechanisms
- [x] You installed using homebridge-config-ui-x
- [x] You enabled homebridge debug output

**Describe the bug**

On homebridge start/plugin init:
```
[7/29/2021, 3:09:43 PM] [Onkyo] start PWR polling..
[7/29/2021, 3:09:43 PM] [Onkyo] event - PWR status poller - new state:  false
[7/29/2021, 3:09:43 PM] [Onkyo] getPowerState - actual mode, return state:  false
[7/29/2021, 3:09:43 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) Zone: main | Command: system-power | Argument: query
[7/29/2021, 3:09:43 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "PWRQSTN"
[7/29/2021, 3:09:43 PM] [Onkyo] start INPUT polling..
[7/29/2021, 3:09:43 PM] [Onkyo] getInputState - actual mode, return i_state:  null
[7/29/2021, 3:09:43 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) Zone: main | Command: input-selector | Argument: query
[7/29/2021, 3:09:43 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "SLIQSTN"
[7/29/2021, 3:09:43 PM] [Onkyo] event - INPUT status poller - new i_state:  null
[7/29/2021, 3:09:43 PM] [homebridge-onkyo] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[7/29/2021, 3:09:43 PM] [homebridge-onkyo] Error: 
    at ActiveIdentifier.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at ActiveIdentifier.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at ActiveIdentifier.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at OnkyoAccessory.getInputSource (/homebridge/node_modules/homebridge-onkyo/index.js:741:70)
    at pollingtoevent.longpolling (/homebridge/node_modules/homebridge-onkyo/index.js:261:10)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-onkyo/node_modules/polling-to-event/index.js:77:5)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

Followed by:
```
[7/29/2021, 3:09:43 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "MVLQSTN"
[7/29/2021, 3:09:43 PM] [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
[7/29/2021, 3:09:43 PM] [Onkyo] getPowerState - PWR QRY: ERROR - current state: false
[7/29/2021, 3:09:43 PM] [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLIQSTN"
[7/29/2021, 3:09:43 PM] [Onkyo] getInputState - INPUT QRY: ERROR - current i_state: 1
[7/29/2021, 3:09:43 PM] [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "AMTQSTN"
[7/29/2021, 3:09:43 PM] [Onkyo] getMuteState - MUTE QRY: ERROR - current m_state: false
[7/29/2021, 3:09:43 PM] [Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "MVLQSTN"
[7/29/2021, 3:09:43 PM] [Onkyo] getVolumeState - VOLUME QRY: ERROR - current v_state: 0
```

Then continuous spamming of eventError:
```
7/29/2021, 3:11:27 PM] [Onkyo] eventError: ERROR (server_error) Server error on 10.0.0.46:60128 - Error: connect ETIMEDOUT 10.0.0.46:60128
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.0.0.46',
  port: 60128
}
[7/29/2021, 3:11:27 PM] [Onkyo] eventDebug: INFO (disconnected) Disconnected from 10.0.0.46:60128
[7/29/2021, 3:11:27 PM] [Onkyo] eventClose: 10.0.0.46
[7/29/2021, 3:11:32 PM] [Onkyo] eventDebug: INFO (connecting) Connecting to 10.0.0.46:60128 (model: TX-NR515)
```

**To Reproduce**
Information on your Onkyo receiver:
1. Onkyo TX-NR515

Information on your configuration:
1. Running the following plugins:
- Homebridge Broadlink Rm Pro 
- Homebridge Simple Wled 
- Trying to setup Homebridge Onkyo 

**Expected behavior**
Onkyo control

**Screenshots**

**Additional context**
Homebridge-onkyo config:
```
{
    "receivers": [
        {
            "name": "Receiver",
            "model": "TX-NR515",
            "ip_address": "--.-.-.--",
            "inputs": [
                {
                    "input_name": "TV/CD",
                    "display_name": "TV/CD"
                }
            ],
            "default_input": "TV/CD",
            "filter_inputs": true,
            "default_volume": 30,
            "max_volume": 60,
            "volume_dimmer": true,
            "volume_speed": false,
            "map_volume_100": true,
            "poll_status_interval": "5000",
            "zone": "main"
        }
    ],
    "platform": "Onkyo"
}
```

Full config (sensitive parts striped out):
```
{
    "bridge": {
        "name": "Homebridge 0865",
        "username": "-",
        "port": -,
        "pin": "-"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "WLED",
            "wleds": [
                {
                    "name": "Plank",
                    "host": [
                        "--.-.-.--",
                        "--.-.-.--"
                    ],
                    "log": true
                }
            ]
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "hosts": [
                {
                    "address": "--.-.-.--",
                    "mac": "--:--:--:--:--:--",
                    "isRFSupported": true
                }
            ],
            "accessories": [
                {
                    "name": "Sony A/V",
                    "type": "tv",
                    "subType": "receiver",
                    "data": {
                        "off": "2600880051112a1215112913151329111611171115121612151216122a1228131512150002c05211291216122812161229131413151217101712141216122a102a121512150002c15212281215122a1215112a121512161116121611161215122a1228121612150002c15112291215122a1117102a1314121611161216111611171228132812161314000d05",
                        "on": "2600880051112a1215112913151329111611171115121612151216122a1228131512150002c05211291216122812161229131413151217101712141216122a102a121512150002c15212281215122a1215112a121512161116121611161215122a1228121612150002c15112291215122a1117102a1314121611161216111611171228132812161314000d05",
                        "remote": {
                            "select": "HEX...",
                            "arrowUp": "HEX...",
                            "arrowDown": "HEX...",
                            "arrowLeft": "HEX...",
                            "arrowRight": "HEX...",
                            "back": "HEX...",
                            "exit": "HEX...",
                            "playPause": "HEX...",
                            "info": "HEX..."
                        },
                        "volume": {
                            "up": "260066004f1216112a1314121513291215121512171115131512151229122a131412160002d3511215122912161215122912161216111514151115121612291328121611160002d54f1315112a12151215122a121512161116121710161315112a112a11161215000d050000",
                            "down": "26006600501427132814141314142713151314131512151413131612281328131512160002c14f132912281315131413281316111613141216111513151427122a121414130002c251122a1029131611151428111612161117111512161215122a112b10161216000d050000"
                        },
                        "inputs": [
                            {
                                "name": "Spotify",
                                "type": "tuner",
                                "data": "260066005112291215122913151315112912161215141511151216112a1229121512160002c0501229131710291316111612281316111611161116121513281229141412150002c15111291216122912151216112a121611161116121514141229122a11161117000d050000"
                            },
                            {
                                "name": "Apple TV",
                                "type": "tuner",
                                "data": "2600660052101612291215121612151328121711151216131412171029122a131412160002d3511215122912161215121612291215131512151215131512291229121613140002d45113141229131511161215122913151217101612151216122a112912151216000d050000"
                            },
                            {
                                "name": "PC",
                                "type": "tuner",
                                "data": "260088004f1216112b1016132a1015122a122a111513141217111512291328121711160002ac5210171228121512291216122913281314121712141215122a1229131610160002ac511117112a1214132911161329112b11151215131610171129122a121412160002ac5112161328111612291215122a112a12161116121513151228122912171115000d05"
                            }
                        ]
                    }
                }
            ]
        },
        {
            "receivers": [
                {
                    "name": "Receiver",
                    "model": "TX-NR515",
                    "ip_address": "10.0.0.46",
                    "inputs": [
                        {
                            "input_name": "TV/CD",
                            "display_name": "TV/CD"
                        }
                    ],
                    "default_input": "TV/CD",
                    "filter_inputs": true,
                    "default_volume": 30,
                    "max_volume": 60,
                    "volume_dimmer": true,
                    "volume_speed": false,
                    "map_volume_100": true,
                    "poll_status_interval": "5000",
                    "zone": "main"
                }
            ],
            "platform": "Onkyo"
        }
    ]
}```

**Comment by cbrandlehner** [comment]
The debug output says that the plugin has issues reaching out to your device using IP 10.0.0.46.
This is most likely a network issue. Are you able to successfully ping 10.0.0.46 while seeing the problem with the plugin?

**Comment by schneideris** [comment]
This appears to be similar to [https://github.com/ToddGreenfield/homebridge-onkyo/issues/134](url).  I am seeing the same issue and would like to hear if anyone has resolved this via configuration?
