### ISSUE TITLE
TX-NR636 not connecting

### ISSUE THREAD

**Issue by iondarie** [ToddGreenfield/homebridge-onkyo#14]
Hello,

I own a TX-NR636, i installed the plugin in homebridge and configured it, but unfortunately i cannot do anything with the plugin except turn on/off the receiver.

Am i doing something wrong?

**Comment by ToddGreenfield** [comment]
Have you tried using another app like Elgato EVE to setup scenes or other dummy switches? The Home app only allows power on/off so you need to use Eve or something that supports more functionality.

**Comment by Hochiss** [comment]
same as OP, please advice:
 
here is the error message:

Error: Cannot find module '../eiscp/eiscp-commands.json'                          
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)                           
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)                                      
    at Module.require (internal/modules/cjs/loader.js:692:17)                                             
    at require (internal/modules/cjs/helpers.js:25:18)                                                    
    at new HttpStatusAccessory (/homebridge/node_modules/homebridge-onkyo/index.js:84:18)                 
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)              
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)                            
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)                           
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)                   
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by toshibochan** [comment]
You can use https://github.com/solowalker27/homebridge-onkyo

For install you can do:
sudo su
sudo npm install -g --unsafe-perm https://github.com/solowalker27/homebridge-onkyo.git
