### ISSUE TITLE
Including zone3 in setup crashes plugin (using valid zone3-enabled set8 models)

### ISSUE THREAD

**Issue by gymrat801** [ToddGreenfield/homebridge-onkyo#149]
When I select a model from the config list that supports Zone3 (set8) and restart Homebridge I receive the following error:
```
[37m[1/4/2022, 10:48:52 PM] [39m[31mTypeError: Cannot read property 'power' of undefined[39m
[31m    at new OnkyoAccessory (/usr/local/lib/node_modules/homebridge-onkyo/index.js:140:40)[39m
[31m    at /usr/local/lib/node_modules/homebridge-onkyo/index.js:37:22[39m
[31m    at Array.forEach (<anonymous>)[39m
[31m    at OnkyoPlatform.createAccessories (/usr/local/lib/node_modules/homebridge-onkyo/index.js:30:13)[39m
[31m    at new OnkyoPlatform (/usr/local/lib/node_modules/homebridge-onkyo/index.js:23:8)[39m
[31m    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40[39m
[31m    at Array.forEach (<anonymous>)[39m
[31m    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)[39m
[31m    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)[39m
```
This happens on every single model that I tried (out of about 15). I also attempted the same with zone3 and zone4 using models in set10, with exactly the same results. 

If I change a functioning zone2 receiver (from set8), updating the zone from zone2 to zone3, the functioning receiver then starts throwing the same error above. This is the same basic error that I get when I zone2 in the config of a model that is not zone2-enabled, just that this time I've made sure I was using a valid model.

Any ideas what might be wrong? It's been driving me insane.

Thanks in advance!

**Comment by gymrat801** [comment]
The error has slightly changed, but the effect is still the same. Adding any model # with a valid zone3 in the config file results in the plugin crashing Homebridge and an endless cycle of restarting.

`[6/4/2022, 1:09:03 PM] [Onkyo] **************************************************************
[6/4/2022, 1:09:03 PM] [Onkyo]   homebridge-onkyo version 2022.18.1
[6/4/2022, 1:09:03 PM] [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
[6/4/2022, 1:09:03 PM] [Onkyo] **************************************************************
[6/4/2022, 1:09:03 PM] [Onkyo] start success...
[6/4/2022, 1:09:03 PM] TypeError: Cannot read properties of undefined (reading 'power')
    at new OnkyoAccessory (/usr/local/lib/node_modules/homebridge-onkyo/index.js:140:40)
    at /usr/local/lib/node_modules/homebridge-onkyo/index.js:37:22
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/usr/local/lib/node_modules/homebridge-onkyo/index.js:30:13)
    at new OnkyoPlatform (/usr/local/lib/node_modules/homebridge-onkyo/index.js:23:8)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:442:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:161:29)`
