### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'some')

### ISSUE THREAD

**Issue by dsaniel** [ToddGreenfield/homebridge-onkyo#181]
**Confirm you have checked the WIKI for troubleshooting first**
_Fill out and check (`[x]`) the boxes which apply.
- Homebridge version: v1.5.0
- Plugin version: 2022.18.1
- OS, including release name/version: Linux homebridgepi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
- [x] Homebridge-Onkyo installed via OS/distribution mechanisms
- [x] You installed using homebridge-config-ui-x
- [ ] You enabled homebridge debug output

**Describe the bug**

**To Reproduce**
Information on your Onkyo receiver:
1. Model information
TX-NR646 (Ethernet)

Information on your configuration:
1. Homebridge config
{
    "receivers": [
        {
            "name": "Receiver",
            "model": "TX-NR646",
            "ip_address": "192.168.1.44",
            "filter_inputs": true,
            "max_volume": 30,
            "volume_type": "none",
            "zone": "main"
        }
    ],
    "platform": "Onkyo"
}

Information from the log:
[7/3/2022, 6:55:45 PM] [Onkyo] Initializing Onkyo platform...
[7/3/2022, 6:55:45 PM] [Onkyo] **************************************************************
[7/3/2022, 6:55:45 PM] [Onkyo]   homebridge-onkyo version 2022.18.1
[7/3/2022, 6:55:45 PM] [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
[7/3/2022, 6:55:45 PM] [Onkyo] **************************************************************
[7/3/2022, 6:55:45 PM] [Onkyo] start success...
[7/3/2022, 6:55:45 PM] TypeError: Cannot read properties of undefined (reading 'some')
    at /var/lib/homebridge/node_modules/homebridge-onkyo/index.js:796:24
    at Array.filter (<anonymous>)
    at OnkyoAccessory.addSources (/var/lib/homebridge/node_modules/homebridge-onkyo/index.js:795:38)
    at OnkyoAccessory.setUp (/var/lib/homebridge/node_modules/homebridge-onkyo/index.js:158:8)
    at new OnkyoAccessory (/var/lib/homebridge/node_modules/homebridge-onkyo/index.js:145:8)
    at /var/lib/homebridge/node_modules/homebridge-onkyo/index.js:37:22
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/var/lib/homebridge/node_modules/homebridge-onkyo/index.js:30:13)
    at new OnkyoPlatform (/var/lib/homebridge/node_modules/homebridge-onkyo/index.js:23:8)
    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:473:40

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Goobaroo** [comment]
It's crashing because `inputs` is not defined.  It's not listed as required but it is needed.

**Comment by dsaniel** [comment]
I see, thanks!
