### ISSUE TITLE
TypeError after updating to version 0.7.7

### ISSUE THREAD

**Issue by BenS89** [ToddGreenfield/homebridge-onkyo#43]
After updating to version 0.7.7, I get the following error in the homebridge log:

`[2020-2-13 10:35:27] TypeError: Cannot read property 'forEach' of undefined
    at new OnkyoAccessory (/usr/lib/node_modules/homebridge-onkyo/index.js:72:22)
    at /usr/lib/node_modules/homebridge-onkyo/index.js:36:22
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/usr/lib/node_modules/homebridge-onkyo/index.js:35:13)
    at new OnkyoPlatform (/usr/lib/node_modules/homebridge-onkyo/index.js:28:8)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
`

The used config is the following

` {
            "platform": "Onkyo",
            "receivers": [
                {
                    "model": "TX-NR609",
                    "ip_address": "192.168.xxx.xxx",
                    "poll_status_interval": "3000",
                    "name": "Anlage",
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true
                }
            ]
        }`

**Comment by BenS89** [comment]
Adding the `inputs` array solved the problem. Seems like this parameter is not optional anymore.
