### ISSUE TITLE
2021.2.1 crashes

### ISSUE THREAD

**Issue by cbrandlehner** [ToddGreenfield/homebridge-onkyo#95]
Unfortunately this version crashes with my configuration:

```
1/10/2021, 1:58:33 PM] [Onkyo] Initializing Onkyo platform...
[1/10/2021, 1:58:33 PM] [Onkyo] Creating 1 receivers...
[1/10/2021, 1:58:33 PM] [Onkyo] Creating new connection for ip 192.168.71.105
[1/10/2021, 1:58:34 PM] [Onkyo] **************************************************************
[1/10/2021, 1:58:34 PM] [Onkyo]   homebridge-onkyo version 2021.2.1
[1/10/2021, 1:58:34 PM] [Onkyo]   GitHub: https://github.com/ToddGreenfield/homebridge-onkyo 
[1/10/2021, 1:58:34 PM] [Onkyo] **************************************************************
[1/10/2021, 1:58:34 PM] [Onkyo] start success...
[1/10/2021, 1:58:34 PM] [Onkyo] Debug mode enabled
[1/10/2021, 1:58:34 PM] [Onkyo] name LAB-Onkyo
[1/10/2021, 1:58:34 PM] [Onkyo] IP 192.168.71.105
[1/10/2021, 1:58:34 PM] [Onkyo] Model TX-NR609
[1/10/2021, 1:58:34 PM] [Onkyo] Zone main
[1/10/2021, 1:58:34 PM] [Onkyo] volume_dimmer: false
[1/10/2021, 1:58:34 PM] [Onkyo] filter_inputs: false
[1/10/2021, 1:58:34 PM] [Onkyo] poll_status_interval: 240
[1/10/2021, 1:58:34 PM] [Onkyo] defaultInput: TV/CD
[1/10/2021, 1:58:34 PM] [Onkyo] defaultVolume: 25
[1/10/2021, 1:58:34 PM] [Onkyo] maxVolume: 45
[1/10/2021, 1:58:34 PM] [Onkyo] mapVolume100: true
[1/10/2021, 1:58:34 PM] TypeError: this.poll_status_interval.parseInt is not a function
    at new OnkyoAccessory (/home/christian/homebridge-onkyo/index.js:134:45)
    at /home/christian/homebridge-onkyo/index.js:37:22
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/home/christian/homebridge-onkyo/index.js:30:13)
    at new OnkyoPlatform (/home/christian/homebridge-onkyo/index.js:23:8)
    at /home/christian/.nvm/versions/node/v14.9.0/lib/node_modules/homebridge/src/server.ts:412:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/home/christian/.nvm/versions/node/v14.9.0/lib/node_modules/homebridge/src/server.ts:389:27)
    at Server.start (/home/christian/.nvm/versions/node/v14.9.0/lib/node_modules/homebridge/src/server.ts:162:29)
    at cli (/home/christian/.nvm/versions/node/v14.9.0/lib/node_modules/homebridge/src/cli.ts:80:10)
[1/10/2021, 1:58:34 PM] Got SIGTERM, shutting down Homebridge...
```

node version: v14.9.0

Crash is caused by line 134 in index.js
`this.interval = this.poll_status_interval.parseInt(10);`

**Comment by cbrandlehner** [comment]
fixed in 2021.2.2
