### ISSUE TITLE
getting warnings all the time in HB UI

### ISSUE THREAD

**Issue by sblitzer** [ToddGreenfield/homebridge-onkyo#98]
For some time (3 weeks) I'm getting this warning in the HB
js ver: v12.19.0
npm ver: v6.14.10

[2/20/2021, 4:17:01 PM] [Onkyo] getPowerState - actual mode, return state:  false
[2/20/2021, 4:17:01 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) Zone: main | Command: system-power | Argument: query
[2/20/2021, 4:17:01 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "PWRQSTN"
[2/20/2021, 4:17:01 PM] [Onkyo] getInputState - actual mode, return i_state:  null
[2/20/2021, 4:17:01 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) Zone: main | Command: input-selector | Argument: query
[2/20/2021, 4:17:01 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "SLIQSTN"
[2/20/2021, 4:17:02 PM] [homebridge-onkyo] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics See https://git.io/JtMGR for more info.
[2/20/2021, 4:17:02 PM] [homebridge-onkyo] Error: 
    at ActiveIdentifier.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2063:79)
    at ActiveIdentifier.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1863:14)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at OnkyoAccessory.getInputSource (/usr/lib/node_modules/homebridge-onkyo/index.js:731:3)
    at ActiveIdentifier.emit (events.js:314:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1466:14
    at new Promise (<anonymous>)
    at ActiveIdentifier.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1464:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
[2/20/2021, 4:17:02 PM] [homebridge-onkyo] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics See https://git.io/JtMGR for more info.
[2/20/2021, 4:17:02 PM] [homebridge-onkyo] Error: 
    at ActiveIdentifier.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2063:79)
    at ActiveIdentifier.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1863:14)
    at ActiveIdentifier.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1338:20)
    at OnkyoAccessory.getInputSource (/usr/lib/node_modules/homebridge-onkyo/index.js:734:70)
    at ActiveIdentifier.emit (events.js:314:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1466:14
    at new Promise (<anonymous>)
    at ActiveIdentifier.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1464:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
[2/20/2021, 4:17:02 PM] [Onkyo] getMuteState - actual mode, return m_state:  false
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) Zone: main | Command: audio-muting | Argument: query
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "AMTQSTN"
[2/20/2021, 4:17:02 PM] [Onkyo] getVolumeState - actual mode, return v_state:  0
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) Zone: main | Command: master-volume | Argument: query
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "MVLQSTN"
[2/20/2021, 4:17:02 PM] [Onkyo] getMuteState - actual mode, return m_state:  false
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) Zone: main | Command: audio-muting | Argument: query
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "AMTQSTN"
[2/20/2021, 4:17:02 PM] [Onkyo] getVolumeState - actual mode, return v_state:  0
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) Zone: main | Command: master-volume | Argument: query
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (command_to_iscp) raw command "MVLQSTN"
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (sent_command) Sent command to 192.168.1.60:60128 - PWRQSTN
[2/20/2021, 4:17:02 PM] [Onkyo] eventDebug: DEBUG (received_data) Received data from 192.168.1.60:60128 - {"command":"system-power","argument":["standby","off"],"iscp_command":"PWR00","host":"192.168.1.60","port":60128,"model":"TX-NR609"}
[2/20/2021, 4:17:02 PM] [Onkyo] eventSystemPower - message: [ 'standby', 'off' ], new state false
[2/20/2021, 4:17:03 PM] [Onkyo] eventDebug: DEBUG (sent_command) Sent command to 192.168.1.60:60128 - SLIQSTN
[2/20/2021, 4:17:03 PM] [Onkyo] eventDebug: DEBUG (received_data) Received data from 192.168.1.60:60128 - {"command":"input-selector","argument":["cd","tv/cd"],"iscp_command":"SLI23","host":"192.168.1.60","port":60128,"model":"TX-NR609"}
[2/20/2021, 4:17:03 PM] [Onkyo] Event - Input changed: cd
[2/20/2021, 4:17:03 PM] [Onkyo] eventInput - message: [ 'cd', 'tv/cd' ] - new i_state: 7 - input: cd
[2/20/2021, 4:17:03 PM] [Onkyo] eventDebug: DEBUG (sent_command) Sent command to 192.168.1.60:60128 - AMTQSTN
[2/20/2021, 4:17:03 PM] [Onkyo] eventDebug: DEBUG (received_data) Received data from 192.168.1.60:60128 - {"command":"audio-muting","argument":"off","iscp_command":"AMT00","host":"192.168.1.60","port":60128,"model":"TX-NR609"}
[2/20/2021, 4:17:03 PM] [Onkyo] eventAudioMuting - message: off, new m_state false
[2/20/2021, 4:17:03 PM] [homebridge-onkyo] This plugin generated a warning from the characteristic 'Mute': Characteristic not in required or optional characteristic section for service Television. Adding anyway. See https://git.io/JtMGR for more info.
[2/20/2021, 4:17:04 PM] [Onkyo] eventDebug: DEBUG (sent_command) Sent command to 192.168.1.60:60128 - MVLQSTN
[2/20/2021, 4:17:04 PM] [Onkyo] eventDebug: DEBUG (received_data) Received data from 192.168.1.60:60128 - {"command":"master-volume","argument":17,"iscp_command":"MVL11","host":"192.168.1.60","port":60128,"model":"TX-NR609"}
[2/20/2021, 4:17:04 PM] [Onkyo] eventVolume - message: 17, new v_state 28 PERCENT
[2/20/2021, 4:17:04 PM] [homebridge-onkyo] This plugin generated a warning from the characteristic 'Volume': Characteristic not in required or optional characteristic section for service Television. Adding anyway. See https://git.io/JtMGR for more info.
[2/20/2021, 4:17:04 PM] [Onkyo] eventDebug: DEBUG (sent_command) Sent command to 192.168.1.60:60128 - AMTQSTN
[2/20/2021, 4:17:04 PM] [Onkyo] eventDebug: DEBUG (received_data) Received data from 192.168.1.60:60128 - {"command":"audio-muting","argument":"off","iscp_command":"AMT00","host":"192.168.1.60","port":60128,"model":"TX-NR609"}
[2/20/2021, 4:17:04 PM] [Onkyo] eventAudioMuting - message: off, new m_state false
[2/20/2021, 4:17:05 PM] [Onkyo] eventDebug: DEBUG (sent_command) Sent command to 192.168.1.60:60128 - MVLQSTN
[2/20/2021, 4:17:05 PM] [Onkyo] eventDebug: DEBUG (sent_command) Sent command to 192.168.1.60:60128 - MVLQSTN
[2/20/2021, 4:17:05 PM] [Onkyo] eventDebug: DEBUG (received_data) Received data from 192.168.1.60:60128 - {"command":"master-volume","argument":17,"iscp_command":"MVL11","host":"192.168.1.60","port":60128,"model":"TX-NR609"}
[2/20/2021, 4:17:05 PM] [Onkyo] eventVolume - message: 17, new v_state 28 PERCENT

**Comment by solowalker27** [comment]
The null warnings we may be able to do something about. It's possible we're passing some null values initially or in certain situations if they're not updated correctly (errors in connection to the receiver, for example).

For the rest, see https://github.com/ToddGreenfield/homebridge-onkyo/issues/100#issuecomment-815008254
